PPG_time_5min_model = PPG_time_5min; % Timestamp from PPG data.
% PPG_pkloc_5min = []; % Same PPG peak location for 5-min.
% PPG_HR_5min = []; % Same.
% PPG_pkloc_5min_L_array = []; % Same
% PPG_pkloc_5min_R_array = []; % Same
ECG_time_5min = ECG_filt_sig_5min;
% ECG_pkloc_5min = []; % Same
% ECG_init_datetime = []; % Same
% ECG_HR_5min = []; % Same
model_add_sec_array = zeros(size(PPG_pkloc_5min_L_array,1),1);
clean_segs = [1:size(PPG_pkloc_5min_L_array,1)]'; % I assume all segments are clean.
clean_segs = clean_segs(:);
% PPG_time_5min_L_array = []; % Same
% PPG_time_5min_R_array = []; % Same
ECG_pkloc_5min_L_array = [];
ECG_pkloc_5min_R_array = [];
show_ECG_min_left = [];

addpath('..\fine_tune_alignment\func');
    [xcorr_model_add_sec,...
        xcorr_add_secs_candidates,...
        xcorr_scores_full,...
        temp_intp_num,...
        max_idx,...
        base_time_diff,...
        xcorr_shift_datetime] = time_seg_xcorr_eval_interp_at_begin_initial_alignment(PPG_time_5min_model, PPG_pkloc_5min, PPG_HR_5min,...
        PPG_pkloc_5min_L_array, PPG_pkloc_5min_R_array,...
        ECG_time_5min, ECG_pkloc_5min, ECG_init_datetime,...
        ECG_HR_5min, model_add_sec_array, clean_segs, 2,...
        PPG_time_5min_L_array,PPG_time_5min_R_array,...
        ECG_pkloc_5min_L_array,ECG_pkloc_5min_R_array,...
        show_ECG_min_left); % time_seg_xcorr_eval_interp_at_begin
    
    % I should loop through all high xcorr points.